top画面の作成
Shu1512/website pull request #23
Opened 2022-09-02 15:14 UTC by hiromichi-hayashi

追加内容

- top画面の作成
- keyVisualコンポーネントを作成
- topで使用する画像の名前を修正
- topのテキストにアニメーションを追加

懸念点

keyVisualコンポーネントのkeyVisualAnimationの最適化

2022-09-03 15:18 UTC, Apro-yuto requested changes

2022-09-03 15:18 UTC, Apro-yuto commented on components/Top/KeyVisual.jsx
> +      { x: 0, y: 0, duration: 0.4, ease: 'elastic.out(0.4, 0.5)' }
@hiromichi-hayashi  
もっとアニメーション早くないと終わるまでにセクション移動されちゃいそう。てかアニメーション結構長い。1秒くらいに短縮したいので、durationとpositionの引数を渡すなりして短縮してください。

2022-09-03 15:18 UTC, Apro-yuto commented on components/Top/KeyVisual.jsx
> +      { y: -1000 },
@hiromichi-hayashi 
-100vh じゃダメですか？(以降同様)
```suggestion
      { y: -100vh },
```

2022-09-03 15:18 UTC, Apro-yuto commented on data/Top.js
> +      id: 1,
@hiromichi-hayashi 
idいる、、、？

2022-09-03 15:34 UTC, Apro-yuto requested changes
@hiromichi-hayashi 
一旦コードは全て無視して、挙動確認しました。
修正お願いします。

2022-09-03 15:34 UTC, Apro-yuto commented on components/Top/index.jsx
> +    <div className="flex h-screen w-full flex-wrap bg-blue-1">
@hiromichi-hayashi 
4Kで見ると崩れてます。
justify-content: center; と align-items: center;を当てれば中央になるかと。

<img width="2546" alt="スクリーンショット 2022-09-04 0 29 22" src="https://user-images.githubusercontent.com/84962399/188277570-d55575cc-22c9-4799-b69b-f60b39bfd88a.png">

2022-09-03 15:34 UTC, Apro-yuto commented on components/Top/index.jsx
> +          <p id="mainText" className="mb-2 text-3XL"></p>
@hiromichi-hayashi 
SP時、実機で試してください。
若干文字小さめな気がします。

![IMG_97761EB65E2E-1](https://user-images.githubusercontent.com/84962399/188277684-d3413fc6-5afe-4bf6-90dc-7d67034d0d8d.jpeg)

2022-09-03 21:50 UTC, hiromichi-hayashi commented
@Apro-yuto 

指摘箇所修正したので確認お願いします

-  アニメーション時間を短縮
- 画面サイズに応じてkeyVisualの位置を調整するよう修正
- sp時のテキストの大きさを変更

idはgsapを適用するときに使っているため残しています
開始位置を-100vhにしたところ挙動がかくつくので-1000のままにしてあります

2022-09-04 03:11 UTC, Apro-yuto commented
@hiromichi-hayashi 
アニメーション時間を短縮
をもっと短縮して

2022-09-04 03:11 UTC, Apro-yuto commented
```
idはgsapを適用するときに使っているため残しています
```
100%必要ないから消して

2022-09-04 03:14 UTC, Apro-yuto commented
開始位置を-100vhにしたところ挙動がかくつく
挙動の動画送って

2022-09-04 03:14 UTC, Apro-yuto commented
@hiromichi-hayashi 
そのほかはいい感じ！
上記3点修正お願いします。

2022-09-04 04:28 UTC, hiromichi-hayashi commented
@Apro-yuto 
指摘箇所修正したので確認お願いします

- idの削除
- アニメーションの速度短縮
- 初期位置を-100vhに変更

動作確認したところ-100vhにしても挙動が変にならなかったのでpcの問題だったかも

2022-09-04 14:06 UTC, merged