Feature/service screen creation
Shu1512/website pull request #24
Opened 2022-09-03 06:13 UTC by Shu1512

2022-09-03 16:54 UTC, Apro-yuto requested changes
@Shu1512 
指摘箇所多くなりそうなので、一旦ここら辺で修正してみてください。
paginationボタン(←、→)を複数回押されるとバグるので直してください。

2022-09-03 16:54 UTC, Apro-yuto commented on components/Service/Service.jsx
> +  const [tl] = useState(gsap.timeline({ paused: true }))
@Shu1512 
これUseStateで囲う必要ありますか？

2022-09-03 16:54 UTC, Apro-yuto commented on components/Service/Service.jsx
> +  const nextPage = () => {
@Shu1512 
ここら辺も外部関数化したら幸せになれる。

2022-09-03 16:54 UTC, Apro-yuto commented on components/Service/Service.jsx
> +          {navigationList.map((_, index) => (
@Shu1512 
ここで、[1~5]が入っている配列を回すという設計にすると、serviceListsが増えても下のpaginationは増えないですよね、、？
理想はserviceListsの数に応じて下のpaginationが増減する、だと思います。

2022-09-03 16:54 UTC, Apro-yuto commented on components/Service/Service.jsx
> +                'border',
枠いらないかもね、、、？

2022-09-03 16:54 UTC, Apro-yuto commented on data/service.js
> +export const navigationList = [1, 2, 3, 4, 5]
不要

2022-09-03 16:54 UTC, Apro-yuto commented on components/Service/Service.jsx
> +      gsap.set(item, { x: isSp ? 10 * index : 30 * index })
マジックナンバーは外部定数化しよう。
https://wa3.i-3-i.info/word12868.html

2022-09-03 16:54 UTC, Apro-yuto commented on components/Service/Service.jsx
> +          opacity: 0,
autoAlphaの方が、visibilityプロパティも同時に変更してくれるぽいので推奨されてます。
https://greensock.com/forums/topic/15361-understanding-autoalpha/

2022-09-03 16:54 UTC, Apro-yuto commented on components/Service/Service.jsx
> +            disabled={pageCount === 4}
@Shu1512 
無限にスライドできる様にはしませんか？

2022-09-03 16:54 UTC, Apro-yuto commented on components/Service/Service.jsx
> +          {navigationList.map((_, index) => (
自分のサイトでもやってるけど、下記の様に修正するといけるかもしれません！
```suggestion
          {[...Array(navigationList.length)].map()
```

2022-09-03 16:54 UTC, Apro-yuto commented on components/Service/Service.jsx
> +          })
@Shu1512 
左に消えるアニメーションと左にずらすアニメーションを一緒に行った方がいいのではないかな
```suggestion
          }, '<')
```

2022-09-03 16:54 UTC, Apro-yuto commented on components/Service/Service.jsx
> +              onClick={() => jumpPage(index)}
←→押した時の挙動逆じゃない？

2022-09-04 02:59 UTC, Shu1512 commented on components/Service/Service.jsx
> +  const [tl] = useState(gsap.timeline({ paused: true }))
@Apro-yuto 
gsap公式の質問サイトで見つけました。
なぜかuseState()を使用しないとうまく動かないんですよね。
ですが、この書き方的にパフォーマンスが悪くなるっぽいので他の方法に変更しました。

2022-09-04 03:20 UTC, Apro-yuto commented on components/Service/Service.jsx
> +  const [tl] = useState(gsap.timeline({ paused: true }))
自分は使わなくても、正常に動いています。
修正お願いします。

2022-09-04 15:07 UTC, merged