FlowCardコンポーネント作成
Shu1512/website pull request #7
Opened 2022-08-18 14:10 UTC by masato5579

@hiromichi-hayashi @Shu1512 

確認願います。

2022-08-22 15:55 UTC, hiromichi-hayashi commented on hooks/useWindowSize.js
> +  useLayoutEffect(() => {
改行の追加お願いします

2022-08-22 16:04 UTC, masato5579 commented
@hiromichi-hayashi 

修正しましたので、ご確認のほどよろしくお願いします。

[1ff9d33](https://github.com/Shu1512/website/pull/7/commits/1ff9d3395d3b18c158d2aea42a0194596a8bc7f7): flow.jsの位置修正
[896b970](https://github.com/Shu1512/website/pull/7/commits/896b9704cacc142912e10b0facbf840f16882739): 改行の追加

2022-08-27 11:28 UTC, Shu1512 commented on hooks/useWindowSize.js
> +  useLayoutEffect(() => {
@masato5579  
`useLayoutEffect`は実行タイミングがレンダリング前で処理を書くと表示速度が落ちる可能性があるので、
`useEffect`を使用してください。
`useEffect`を使用してダメそうだったらこのままでいいのですが。

2022-08-27 11:28 UTC, Shu1512 commented on pages/index.js
>  import { gsap } from 'gsap/dist/gsap'
@masato5579 
ここもついでに消去お願いします。

2022-08-27 11:28 UTC, Shu1512 commented on pages/index.js
>  import { useEffect, useRef } from 'react'
同じく

2022-08-27 11:28 UTC, Shu1512 commented on pages/index.js
>    const boxRef = useRef()
同じく下のuseEffectも消してください。

2022-08-27 11:42 UTC, Shu1512 commented on hooks/useWindowSize.js
> +  const [size, setSize] = useState([0, 0])
@masato5579 
```suggestion
  const [windowSize, setWindowSize] = useState([0, 0])
```

2022-08-27 11:42 UTC, Shu1512 commented on hooks/useWindowSize.js
> +    const updateSize = () => {
```suggestion
    const updateWindowSize = () => {
```

2022-08-28 10:41 UTC, masato5579 commented
vwの関数を本実装に反映して、修正するので、一旦レビューはしなくて大丈夫です。

2022-08-29 16:28 UTC, masato5579 commented
@Shu1512 

指摘箇所修正しました。
ですが、vwに変更する修正が残っているので、
それが反映されて修正したら、まとめてチェックおねがします。

2022-08-31 17:02 UTC, masato5579 commented
@hiromichi-hayashi @Shu1512 
vwに実装を適用しました。
ご確認お願いします。

2022-09-03 14:59 UTC, Apro-yuto requested changes

2022-09-03 14:59 UTC, Apro-yuto commented on components/FlowCard.jsx
> +          className="h-[48px] overflow-y-scroll text-SM sm:h-[75px] md:h-[75px] lg:h-[116px]"
<img width="418" alt="スクリーンショット 2022-09-03 23 46 13" src="https://user-images.githubusercontent.com/84962399/188276096-f7849340-7275-488f-bbdc-1727d0b24188.png">
スクロールバーがかなり邪魔あので、非表示にするよう修正をお願いします。

やり方としては以下のCSSを本個所に適用すればいけます！
```css
{当てたい親要素} {
  -ms-overflow-style: none;
  scrollbar-width: none;
}
{当てたい要素}::-webkit-scrollbar {
    display: none;
}
```

2022-09-03 15:01 UTC, Apro-yuto commented
@masato5579  
スマホの実機で確認してますか？
自分の環境だと大崩れしてます。(iphone 13)
![IMG_3648](https://user-images.githubusercontent.com/84962399/188276418-99b262a5-c2d8-4a64-95ea-ac8b37fd5079.PNG)

2022-09-03 15:02 UTC, Apro-yuto commented
@masato5579  
以上2点の修正だけ一旦お願いします！

2022-09-03 16:21 UTC, masato5579 commented
@Apro-yuto 
> @masato5579 スマホの実機で確認してますか？ 自分の環境だと大崩れしてます。(iphone 13) ![IMG_3648](https://user-images.githubusercontent.com/84962399/188276418-99b262a5-c2d8-4a64-95ea-ac8b37fd5079.PNG)

自分のスマホだといい感じに表示されてます。
表示が崩れているのはHeaderとかFooterとかですね。
そちらは別ブランチで林さん・廣内さんが対応してくれるかと思います。（全体のスタイル調整も含め）
今回は、あくまでFlowCardのコンポーネントの実装なので、
一旦、FlowCardの部分が良ければマージしちゃいたいです。

2022-09-03 16:45 UTC, masato5579 commented
@Apro-yuto 
- https://github.com/Shu1512/website/pull/7#discussion_r962164983
- https://github.com/Shu1512/website/pull/7#issuecomment-1236157475

修正/コメントしましたので、ご確認お願いします

2022-09-03 16:59 UTC, Apro-yuto commented
@masato5579 
OK！マージしてくださいー
スマホのレイアウト崩れはよく把握できないので、一旦大丈夫です！

2022-09-03 18:59 UTC, merged